name: \U+1F913 Thoughts
description: You think of something
title: \U+1F913 Thoughts
labels:
  - Thought
assignees: Angryman18
body:
  - type: textarea
    attributes:
      label: Share your thoughts
    validations:
      required: true
